name: bazel_builder
description: "Dart ❤️ Bazel"
version: 0.0.1
repository: https://github.com/Attempt3035/bazel_builder

environment:
  sdk: ^3.3.0
  flutter: ^3.3.0

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  path: ^1.9.0
  pubspec_yaml: ^3.1.0
  yaml: ^3.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
